#---------------------------------------------------------------------
# Title:         NCATS Complex Shiny Package Loader
# Author:        Brandon Monier
# Author2:       Marissa Hirst
# Author3:       Ben Ernest
# Last Modified: 2020-03-04
# --
# Created:       2018-01-26 11:29:39 CDT
#---------------------------------------------------------------------

library(RMariaDB)

library(crosstalk)
library(dplyr)
library(DT)
library(gtools)
library(plotly)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinythemes)
library(tibble)
library(Rcpp)
library(Hmisc)
library(ggplot2)
library(geneplotter)
library(locfit)
library(GGally)
library(pheatmap)
library(reshape2)
library(backports)
library(digest)
library(fields)
library(psych)
library(DESeq2)
library(edgeR)
library(limma)
library(stringr)
library(tools)
library(openxlsx)
library(Rtsne)
library(WGCNA)
library(flashClust)
library(MCL)
library(kmed)
library(ape)
library(readr)
library(rmarkdown)
library(gplots)
library(RColorBrewer)
library(enrichR)
library(GO.db)
library(scClustViz)
library(data.table)
library(viridis)
library(scales)
library(heatmaply)
library(Seurat)
library(RUVSeq)
library(EDASeq)
library(biomaRt)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(shinyjs)
library(umap)
library(stringi)
library(presto)
library(ComplexHeatmap)
library(purrr)
library(tidyr)
library(xml2)
library(rvest)
library(ggrepel)
library(plotrix)
library(ggdendro)
library(cowplot)
library(dendextend)
library(gridExtra)
library(shinyWidgets)
library(clustree)
library(showtext)
library(gfonts)
library(Cairo)
library(patchwork)
library(MAST)
